### ISSUE TITLE
Error with Latitude 7410

### ISSUE THREAD

**Issue by ashleysommer** [jacekkow/controlvault2-nfc-enable#11]
Latitude 7410 gives:

```
INFO:__main__:Looking for supported device...
INFO:__main__:Found 0A5C:5843
DEBUG:cvcomm:Enumerating interfaces...
Traceback (most recent call last):
  File "./nfc.py", line 62, in <module>
    handler = UsbDeviceFinder.find()
  File "./nfc.py", line 49, in find
    handler = cls._cls_matcher(device)
  File "./nfc.py", line 36, in _cls_matcher
    return matcher.handler(device)
  File "./nfc.py", line 22, in <lambda>
    UsbDeviceMatcher({'idVendor': 0x0A5C, 'idProduct': 0x5843}, lambda device: __import__('cv3').ControlVault3(device)),
  File "/home/ashley/Downloads/controlvault2-nfc-enable/cv3.py", line 26, in __init__
    self.communicator = cvcomm.ControlVaultCommunicator(device)
  File "/home/ashley/Downloads/controlvault2-nfc-enable/cvcomm.py", line 13, in __init__
    self.bulk_in, self.bulk_out = self._find_endpoints()
  File "/home/ashley/Downloads/controlvault2-nfc-enable/cvcomm.py", line 68, in _find_endpoints
    raise Exception('Cannot find vendor-specific interface')
Exception: Cannot find vendor-specific interface
```
Thing is, it not actually clear whether the 7410 even has a NFC reader built in.

**Comment by ashleysommer** [comment]
Update...
I added a debug output the found interfaces:
```
DEBUG:cvcomm:Enumerating interfaces...
DEBUG:cvcomm:Interface     INTERFACE 0: Application Specific ======================
     bLength            :    0x9 (9 bytes)
     bDescriptorType    :    0x4 Interface
     bInterfaceNumber   :    0x0
     bAlternateSetting  :    0x0
     bNumEndpoints      :    0x3
     bInterfaceClass    :   0xfe Application Specific
     bInterfaceSubClass :    0x0
     bInterfaceProtocol :    0x0
     iInterface         :    0x4 Broadcom ControlVault 3 w/FingerPrint
      ENDPOINT 0x81: Bulk IN ===============================
       bLength          :    0x7 (7 bytes)
       bDescriptorType  :    0x5 Endpoint
       bEndpointAddress :   0x81 IN
       bmAttributes     :    0x2 Bulk
       wMaxPacketSize   :  0x200 (512 bytes)
       bInterval        :    0x0
      ENDPOINT 0x1: Bulk OUT ===============================
       bLength          :    0x7 (7 bytes)
       bDescriptorType  :    0x5 Endpoint
       bEndpointAddress :    0x1 OUT
       bmAttributes     :    0x2 Bulk
       wMaxPacketSize   :  0x200 (512 bytes)
       bInterval        :    0x0
      ENDPOINT 0x85: Interrupt IN ==========================
       bLength          :    0x7 (7 bytes)
       bDescriptorType  :    0x5 Endpoint
       bEndpointAddress :   0x85 IN
       bmAttributes     :    0x3 Interrupt
       wMaxPacketSize   :  0x400 (1024 bytes)
       bInterval        :    0x1
DEBUG:cvcomm:Interface     INTERFACE 1: Smart Card ================================
     bLength            :    0x9 (9 bytes)
     bDescriptorType    :    0x4 Interface
     bInterfaceNumber   :    0x1
     bAlternateSetting  :    0x0
     bNumEndpoints      :    0x3
     bInterfaceClass    :    0xb Smart Card
     bInterfaceSubClass :    0x0
     bInterfaceProtocol :    0x0
     iInterface         :    0x5 Contacted SmartCard
      ENDPOINT 0x82: Bulk IN ===============================
       bLength          :    0x7 (7 bytes)
       bDescriptorType  :    0x5 Endpoint
       bEndpointAddress :   0x82 IN
       bmAttributes     :    0x2 Bulk
       wMaxPacketSize   :  0x200 (512 bytes)
       bInterval        :    0x0
      ENDPOINT 0x2: Bulk OUT ===============================
       bLength          :    0x7 (7 bytes)
       bDescriptorType  :    0x5 Endpoint
       bEndpointAddress :    0x2 OUT
       bmAttributes     :    0x2 Bulk
       wMaxPacketSize   :  0x200 (512 bytes)
       bInterval        :    0x0
      ENDPOINT 0x86: Interrupt IN ==========================
       bLength          :    0x7 (7 bytes)
       bDescriptorType  :    0x5 Endpoint
       bEndpointAddress :   0x86 IN
       bmAttributes     :    0x3 Interrupt
       wMaxPacketSize   :  0x400 (1024 bytes)
       bInterval        :    0x1
```
  
Looks like this particular version of the chip exposes the application-specific interface as `0xFE`? I'll keep trying to see what else I find.

**Comment by ashleysommer** [comment]
Changing the script to look for the inteface at address `0xFE` gives:
```
DEBUG:cvcomm:Interface found: INTERFACE 0: Application Specific
DEBUG:cvcomm:Enumerating endpoints...
DEBUG:cvcomm:BULK IN found: ENDPOINT 0x81: Bulk IN
DEBUG:cvcomm:BULK OUT found: ENDPOINT 0x1: Bulk OUT
DEBUG:cvcomm:Endpoint discovery successful.
INFO:__main__:Handler ControlVault3 (Broadcom ControlVault 3)
INFO:__main__:Turning NFC on...
DEBUG:cvcomm:Control: (65, 1, 0, 3) {}
Traceback (most recent call last):
  File "./nfc.py", line 65, in <module>
    handler.turn_on()
  File "/home/ashley/Downloads/controlvault2-nfc-enable/cv3.py", line 29, in turn_on
    self.communicator.ctrl_transfer(0x41, 1, 0, 3)
  File "/home/ashley/Downloads/controlvault2-nfc-enable/cvcomm.py", line 22, in ctrl_transfer
    return self.device.ctrl_transfer(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/usb/core.py", line 1036, in ctrl_transfer
    ret = self._ctx.backend.ctrl_transfer(
  File "/usr/lib/python3/dist-packages/usb/backend/libusb1.py", line 875, in ctrl_transfer
    ret = _check(self.lib.libusb_control_transfer(
  File "/usr/lib/python3/dist-packages/usb/backend/libusb1.py", line 595, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 110] Operation timed out
```

**Comment by ashleysommer** [comment]
I changed the timeout to 10 seconds, and still have the same problem. I'm guessing it needs to have a different turn-on sequence.

**Comment by jacekkow** [comment]
> it not actually clear whether the 7410 even has a NFC reader built in

Specs say "Contacted Smart Card and ControlVault 3" [(specs)](https://www.dell.com/support/manuals/pl-pl/latitude-14-7410-2-in-1-laptop/lati_7410_ss/security?guid=guid-cf12925a-8de4-40c8-8300-9072d34bbbe4&lang=en-us) I don't see any mention of NFC reader. Do you have an icon like the one below somewhere near the keyboard?
![nfc](https://user-images.githubusercontent.com/4353795/104122001-b84e0580-5342-11eb-8392-8d0356c9599d.jpg)

I'd say there is no contactless reader in your laptop - note the interfaces output:
```
    INTERFACE 0: Application Specific ======================
     iInterface         :    0x4 Broadcom ControlVault 3 w/FingerPrint
    INTERFACE 1: Smart Card ================================
     iInterface         :    0x5 Contacted SmartCard
```

Laptops with NFC expose two smart card interfaces plus vendor specific one even before my script is run - like this:
```
    INTERFACE 0: Application Specific ======================
     iInterface         :    0x4 Broadcom USH w/touch sensor
    INTERFACE 1: Smart Card ================================
     iInterface         :    0x5 Contacted SmartCard
    INTERFACE 2: Smart Card ================================
     iInterface         :    0x6 Contactless SmartCard
    INTERFACE 3: Vendor Specific ===========================
     iInterface         :    0x8 Broadcom NFP
```
